### ISSUE TITLE
Quer adotar/manter a lib python-pagseguro?

### ISSUE THREAD

**Issue by rochacbruno** [renzon/pygseguro#1]
Há alguns anos criei a https://github.com/rochacbruno/python-pagseguro

`pip install pagseguro`

é largamente usada, mas está defasada em relação a novas melhorias do pag seguro.

Eu não tenho tempo para manter essa lib (e nem estou usando ela) e parace que os contribuidores atuais também não estão ativos.

Fique a vontade se quiser adotar a lib (transfiro o ownership para vc)

**Comment by renzon** [comment]
Cheguei a dar uma olhada na lib e conversar com o Augusto sobre ela. Mas esse aqui na realidade é um projeto do curso Python Pro para fazer junto com o pessoal, a ideia e mostrar requests, instalar CI e etc. Mas realmente posso dar uma olhada nela e ver se consigo ajudar.
